language: python

sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
      python: "2.7"
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
      python: "3.6"
      compiler: gcc

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
      env:
        - CC=clang-3.8
        - CXX=clang++-3.8
      python: "2.7"
      compiler: clang

install:
  - pip install .

script:
  - pytest
