sudo: false

language: python

install: pip install .[tests]
script: pytest -rsv

matrix:
  include:
    - os: osx
    
    - os: windows
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      install:
        pip install .[tests]
    
    - os: linux
      python: "2.7"

    - os: linux
      python: "3.7"

  allow_failures:
    - os: windows
  fast_finish: true
  
notifications:
  email: false