sudo: false

language: python

git:
  depth: 10
  submodules_depth: 10

matrix:
  include:
    - os: osx
      language: sh
      install: pip install --user .[tests]

    - os: windows
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      install: pip install --user .[tests]
      
    - os: linux
      python: "2.7"
      install: pip install .[tests]

    - os: linux
      python: "3.6"
      install: pip install .[tests]

script: python -m pytest -rsv

notifications:
  email: false