sudo: false

language: python

git:
  depth: 10
  submodules_depth: 10

matrix:
  include:
    - os: osx
      python: "3.6"

    - os: linux
      python: "2.7"

    - os: linux
      python: "3.6"

install:
  - pip install .
  - pip install graphviz
  - pip install --upgrade attrs # hot fix, to be removed once this is fixed in particle

script:
  - pytest

notifications:
  email: false