sudo: false

language: python

matrix:
  include:
    - os: osx
      python: "2.7"

    # - os: osx
    #   python: "3.6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
      python: "2.7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - CC=gcc-6
        - CXX=g++-6
      python: "3.6"

install:
  - pip install .

script:
  - pytest
