sudo: false

language: python

install: pip install .[tests]
script: pytest -rsv tests

matrix:
  include:
    - os: osx
      language: sh # prevent installation of missing python

    - os: windows
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

    - os: linux
      python: "2.7"

    - os: linux
      python: "3.7"

notifications:
  email: false
