sudo: false

language: python

matrix:
  include:
    - os: osx
      language: sh
      install:
        virtualenv build
        source build/bin/activate
        pip install .[tests]

    - os: windows
      language: sh
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
      install:
        virtualenv build
        build/Scripts/activate.bat
        pip install .[tests]
      
    - os: linux
      python: "2.7"
      install: pip install .[tests]

    - os: linux
      python: "3.6"
      install: pip install .[tests]

script: pytest -rsv

notifications:
  email: false